Documentation:
  Enabled: false

Encoding:
  Enabled: false

BlockLength:
  Max: 100

LineLength:
  Max: 200

ClassLength:
  Max: 200

AccessModifierIndentation:
  EnforcedStyle: outdent

IfUnlessModifier:
  Enabled: false

CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: true

MethodLength:
  CountComments: false
  Max: 20

SignalException:
  Enabled: false

ColonMethodCall:
  Enabled: false

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

RegexpLiteral:
  Enabled: false

RedundantBegin:
  Enabled: false

AssignmentInCondition:
  Enabled: false

ParameterLists:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

DoubleNegation:
  Enabled: false

TrivialAccessors:
  ExactNameMatch: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w':    '()'
